// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-activities.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.111.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-activities.ts
var search_activities_default = defineTool({
  name: "search_activities",
  title: "Search activities",
  description: "Search the Vointy activity catalogue the signed-in user can access. Returns id, title, description, unit and points.",
  inputSchema: {
    query: z.string().trim().describe("Free-text search on the activity title.").optional(),
    limit: z.number().int().describe("Maximum number of activities to return (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("activities").select("id,title,description,unit,points,duration_minutes,category").eq("is_active", true).order("title", { ascending: true }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (query) builder = builder.ilike("title", `%${query}%`);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { activities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-activity.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var log_activity_default = defineTool2({
  name: "log_activity",
  title: "Log a performed activity",
  description: "Log a completed activity for the signed-in user. Each logged activity earns 1 Activity Index point.",
  inputSchema: {
    activity_id: z2.string().uuid().describe("Activity id from search_activities."),
    amount: z2.number().describe("Performed amount in the activity's unit (e.g. minutes)."),
    note: z2.string().trim().describe("Optional note about the performance.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ activity_id, amount, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: activity, error: activityError } = await supabase.from("activities").select("id,unit").eq("id", activity_id).maybeSingle();
    if (activityError) return { content: [{ type: "text", text: activityError.message }], isError: true };
    if (!activity) return { content: [{ type: "text", text: "Activity not found" }], isError: true };
    const { data, error } = await supabase.from("performed_exercises").insert({
      user_id: ctx.getUserId(),
      activity_id,
      amount,
      unit: activity.unit,
      note: note ?? null,
      points: 1
    }).select("id,activity_id,amount,unit,points,performed_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged. ${JSON.stringify(data)}` }],
      structuredContent: { performed_exercise: data }
    };
  }
});

// src/lib/mcp/tools/get-activity-index.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_activity_index_default = defineTool3({
  name: "get_activity_index",
  title: "Get my Activity Index",
  description: "Return the signed-in user's Activity Index: total points and points per month for the current calendar year. Every logged activity is worth 1 point.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const year = (/* @__PURE__ */ new Date()).getUTCFullYear();
    const { data, error } = await supabase.from("performed_exercises").select("points,performed_at").eq("user_id", ctx.getUserId()).gte("performed_at", `${year}-01-01`).order("performed_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const monthly = Array.from({ length: 12 }, () => 0);
    let total = 0;
    for (const row of data ?? []) {
      const month = new Date(row.performed_at).getUTCMonth();
      const points = row.points ?? 1;
      monthly[month] += points;
      total += points;
    }
    const summary = { year, total_points: total, monthly_points: monthly };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-challenges.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_challenges_default = defineTool4({
  name: "list_challenges",
  title: "List challenges",
  description: "List challenges visible to the signed-in user, optionally only the ones they have joined.",
  inputSchema: {
    joined_only: z3.boolean().describe("When true, only challenges the user has joined.").optional(),
    limit: z3.number().int().describe("Maximum number of challenges (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ joined_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let joinedIds = null;
    if (joined_only) {
      const { data: data2, error: error2 } = await supabase.from("challenge_participants").select("challenge_id").eq("user_id", ctx.getUserId());
      if (error2) return { content: [{ type: "text", text: error2.message }], isError: true };
      joinedIds = (data2 ?? []).map((row) => row.challenge_id);
      if (joinedIds.length === 0) {
        return {
          content: [{ type: "text", text: "No joined challenges." }],
          structuredContent: { challenges: [] }
        };
      }
    }
    let builder = supabase.from("challenges").select("id,title,description,challenge_type,status,start_date,end_date,target_value,unit").order("start_date", { ascending: false }).limit(max);
    if (joinedIds) builder = builder.in("id", joinedIds);
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { challenges: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/join-challenge.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var join_challenge_default = defineTool5({
  name: "join_challenge",
  title: "Join a challenge",
  description: "Join a challenge as the signed-in user. Use list_challenges to find a challenge id.",
  inputSchema: {
    challenge_id: z4.string().uuid().describe("Challenge id to join.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ challenge_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing, error: existingError } = await supabase.from("challenge_participants").select("id,status,progress").eq("challenge_id", challenge_id).eq("user_id", userId).maybeSingle();
    if (existingError) return { content: [{ type: "text", text: existingError.message }], isError: true };
    if (existing) {
      return {
        content: [{ type: "text", text: "Already joined this challenge." }],
        structuredContent: { participant: existing, already_joined: true }
      };
    }
    const { data, error } = await supabase.from("challenge_participants").insert({ challenge_id, user_id: userId }).select("id,challenge_id,status,progress").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Joined challenge. ${JSON.stringify(data)}` }],
      structuredContent: { participant: data, already_joined: false }
    };
  }
});

// src/lib/mcp/tools/list-community-posts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_community_posts_default = defineTool6({
  name: "list_community_posts",
  title: "List community posts",
  description: "List the most recent community feed posts visible to the signed-in user.",
  inputSchema: {
    limit: z5.number().int().describe("Maximum number of posts (default 20).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("community_posts").select("id,content,image_url,created_at,activity_id,challenge_id").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-community-post.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var create_community_post_default = defineTool7({
  name: "create_community_post",
  title: "Create a community post",
  description: "Publish a post to the Vointy community feed as the signed-in user.",
  inputSchema: {
    content: z6.string().trim().describe("Post text."),
    image_url: z6.string().url().describe("Optional image URL to attach.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content, image_url }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!content) {
      return { content: [{ type: "text", text: "Post content is required" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: profile } = await supabase.from("profiles").select("organization_id").eq("user_id", ctx.getUserId()).maybeSingle();
    const { data, error } = await supabase.from("community_posts").insert({
      user_id: ctx.getUserId(),
      content,
      image_url: image_url ?? null,
      organization_id: profile?.organization_id ?? null
    }).select("id,content,image_url,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Posted. ${JSON.stringify(data)}` }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool8({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Vointy profile: display name, language and organization.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name,language,organization_id,created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = { ...data ?? {}, email: ctx.getUserEmail() ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(profile) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jwzdpmqirvwguftvrvyu";
var mcp_default = defineMcp({
  name: "vointy-wellbeing-boost",
  title: "vointy-wellbeing-boost",
  version: "0.1.0",
  instructions: "Tools for Vointy, a corporate wellbeing platform. Use search_activities and log_activity to record completed activities (1 point each), get_activity_index for the user's Activity Index, list_challenges/join_challenge for challenges, and list_community_posts/create_community_post for the community feed. All tools act as the signed-in Vointy user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    search_activities_default,
    log_activity_default,
    get_activity_index_default,
    list_challenges_default,
    join_challenge_default,
    list_community_posts_default,
    create_community_post_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
